
include: package:lints/recommended.yaml

linter:
  rules:
    # Dokumentation erzwingen
    public_member_api_docs: true
    always_declare_return_types: true
    always_specify_types: true

    void_print: false
    prefer_single_quotes: true
    # public_member_api_docs: true